# Generated by Django 4.2.7 on 2024-04-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_reportcard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_of_report_card_genetation")},
        ),
    ]
