# Generated by Django 4.2.7 on 2024-04-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_reportcard_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="date_of_report_card_genetation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
